controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    group_position_controller:
      type: position_controllers/JointGroupPositionController

    group_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    group_effort_controller:
      type: effort_controllers/JointGroupEffortController

group_position_controller:
  ros__parameters:
    joints:
      - front_left_shoulder_connector
      - front_left_shoulder_leg
      - front_left_knee
      - front_right_shoulder_connector
      - front_right_shoulder_leg
      - front_right_knee
      - rear_left_shoulder_connector
      - rear_left_shoulder_leg
      - rear_left_knee
      - rear_right_shoulder_connector
      - rear_right_shoulder_leg
      - rear_right_knee

group_velocity_controller:
  ros__parameters:
    joints:
      - front_left_shoulder_connector
      - front_left_shoulder_leg
      - front_left_knee
      - front_right_shoulder_connector
      - front_right_shoulder_leg
      - front_right_knee
      - rear_left_shoulder_connector
      - rear_left_shoulder_leg
      - rear_left_knee
      - rear_right_shoulder_connector
      - rear_right_shoulder_leg
      - rear_right_knee

group_effort_controller:
  ros__parameters:
    joints:
      - front_left_shoulder_connector
      - front_left_shoulder_leg
      - front_left_knee
      - front_right_shoulder_connector
      - front_right_shoulder_leg
      - front_right_knee
      - rear_left_shoulder_connector
      - rear_left_shoulder_leg
      - rear_left_knee
      - rear_right_shoulder_connector
      - rear_right_shoulder_leg
      - rear_right_knee
      
joint_trajectory_controller:
  ros__parameters:
    joints:
      - front_left_shoulder_connector
      - front_left_shoulder_leg
      - front_left_knee
      - front_right_shoulder_connector
      - front_right_shoulder_leg
      - front_right_knee
      - rear_left_shoulder_connector
      - rear_left_shoulder_leg
      - rear_left_knee
      - rear_right_shoulder_connector
      - rear_right_shoulder_leg
      - rear_right_knee

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 100.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)